# Generated by Django 2.2.14 on 2020-09-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_address_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='booking',
            field=models.ManyToManyField(to='core.Booking'),
        ),
    ]
