# Generated by Django 2.2.14 on 2020-10-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='being_delivered',
            new_name='confirmOrder',
        ),
        migrations.RemoveField(
            model_name='order',
            name='received',
        ),
    ]
