# Generated by Django 2.2.14 on 2020-09-23 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='apartment_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip',
        ),
        migrations.AddField(
            model_name='address',
            name='cap',
            field=models.CharField(default=40019, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='città',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='n_civico',
            field=models.CharField(default=4, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='address',
            name='piano',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='address',
            name='via',
            field=models.CharField(default=43, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
