# Generated by Django 2.2.14 on 2020-10-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.ManyToManyField(null=True, to='core.Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='booking',
            field=models.ManyToManyField(null=True, to='core.Booking'),
        ),
    ]
