# Generated by Django 2.2.14 on 2020-09-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
